# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa419f7e83eae00653be82e179c05f7858703f8af5a9b015fcef85ac462a42351742c6efa4de27a9f68d5081a6d6a91a75d4cac609ff4caa1a19ffb125b2213

test:
  secret_key_base: 031f2c7cba0df3bb16ee9ec4aabb98f63e64cc37d1881359e1dd08c839d5ea92072a777c8b7ce7372e6b460cc4239d01f777c680de9ce51ac52b2a9bca22b1ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
